# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

module Config
	Target = "EBC_Test"
end

default_platform(:ios)

platform :ios do
  before_all do |lane|
    unless File.zero?("../.xcode-version")
      # xcversion(version: File.read("../.xcode-version"))
    end
  end

  desc "build to firebase"
  lane :beta do |optoins|
    # echo("Branch Name: ${branch}")
    build_beta_to_firebase
  end

  desc "build to testFlight"
  lane :beta_testFlight do |optoins|
    # echo("Branch Name: ${branch}")
    build_beta_to_testFlight
  end

  desc "build release"
  lane :release do |optoins|
    # echo("Branch Name: ${branch}")
    build_release
  end

  def build_beta_to_firebase ()
    puts "出測試版到firebase"
  end

  def build_beta_to_testFlight()
    puts "出測試版到testFlight"
  end

  def build_release_to_testFlight()
    puts "出正式版到testFlight"
  end

  def build_release()
    build_beta_to_firebase
    build_release_to_testFlight
  end
end
